### ISSUE TITLE
Book assumes VSCode but doesn't say so

### ISSUE THREAD

**Issue by dabrahams** [avigad/lamr#6]
Sorry if this is filed in the wrong place.  https://avigad.github.io/lamr/using_lean_as_a_programming_language.html talks about hovering over things and an “ information window” that are confusing for an Emacs user, which is where I started my setup.  It would be good for the book to say up front that it assuming you're using VSCode.  (Also would be very useful if it had an up-front link to the codespaces option for people who want to dive right in)

**Comment by Vtec234** [comment]
I agree it would be good for the book to clarify which editor setups are supported. However, both hovering and the infoview (information window) should work in Emacs with [leanprover-community/lean4-mode](https://github.com/leanprover-community/lean4-mode).

**Comment by dabrahams** [comment]
I had it installed, but I didn't realize I needed to be inside a Lean project for LSP to do its thing.  I do get hovering within the book project.  However, I don't see any buffer corresponding to an “information window.”  What am I missing?

**Comment by dabrahams** [comment]
Ah, never mind, I found toggle info display in the menu.  Thanks!
