### ISSUE TITLE
Is there a way to file PRs against the book?

### ISSUE THREAD

**Issue by dabrahams** [avigad/lamr#7]
I keep running into little things I'd like to offer corrections on (mostly typos) but I don't see a way to do it.

**Comment by avigad** [comment]
Thanks! The source is in a private repository with other material for the course it was designed for. We hope to move it to a new repository and make some substantial revisions before we use it again in the coming calendar year. In the meantime, we'd welcome typos and corrections posted here or emailed directly to me at avigad@cmu.edu.

**Comment by dabrahams** [comment]
I don't know if it helps, but if you wanted to make just the book available for PRs but aren't ready to completely separate it from the other material, you could probably use [git-subtree](https://manpages.debian.org/testing/git-man/git-subtree.1.en.html) to make the book sub-project available as a standalone public repository and merge back into your private repo at your leisure. 

Thanks again.  Feel free to close this unless there's more to say.
