### ISSUE TITLE
Is there an appropriate place to ask questions about the book?

### ISSUE THREAD

**Issue by dabrahams** [avigad/lamr#8]
For example, the exercises in the chapter on using Lean as an FP language contain a couple of "Prove in Lean that…” questions, that seem to require knowledge the book would have contained since it's walking me through the much simpler fundamentals of using Lean to write programs.  I don't know how to approach these exercises.  Should I work through the very substantial [tutorial on Lean theorem proving first](https://leanprover.github.io/theorem_proving_in_lean4/)? It seems like opening issues here must be the wrong vehicle for questions like this one…

**Comment by avigad** [comment]
Most of the book uses Lean as a programming language to implement logic-based algorithms or to connect with SAT- and SMT-solvers. Nothing bad will happen if you ignore the parts that ask you to think about Lean as a proof assistant. But if you do want to learn more about Lean as a proof assistant, I recommend looking at [Mathematics in Lean](https://github.com/leanprover-community/mathematics_in_lean), exploring the [Lean Community web pages](https://leanprover-community.github.io/), and checking out the [Lean Zulip social media channel](https://leanprover.zulipchat.com/).

**Comment by dabrahams** [comment]
Thanks for your advice.

> I recommend looking at [Mathematics in Lean](https://github.com/leanprover-community/mathematics_in_lean),

That's a better place to start than the tutorial I linked?

**Comment by avigad** [comment]
The introduction to MIL explains the difference in approach. TPIL explains the system and its foundations from the bottom up, while MIL is designed to get you proving theorems as quickly as possible. For verifying programs, the Hitchhiker's Guide to Formal Verification in Lean is better. You can find a guide to learning resources [here](https://leanprover-community.github.io/learn.html).

**Comment by dabrahams** [comment]
many thanks!
